INFLUXDB_TOKEN = "iWGU-RZ-AoML0bP4kjabHrqlB3IDtyLPAs_XMDpGOldEvQrzmtwC2Y-4arrkl1BX_bQpEvtYGgh16pJyviIsvA=="
INFLUXDB_HOST = "cluster-id.influxdb.io"
INFLUXDB_ORG = "ContentSquad"
INFLUXDB_DATABASE = "ConversationStore"